### ISSUE TITLE
Improvements for icon/image and tooltip

### ISSUE THREAD

**Issue by k3ypusher** [budlabs/genmonify#3]
It would be great if we could set an image/icon when the actual text content is empty.

An option to disable the tooltip completely would also be very helpful.

**Comment by budRich** [comment]
Yes. Thanks for making the issue, i will try fixing it right away,

**Comment by k3ypusher** [comment]
Thanks for the quick update!

However there seems to be a typo, so it doesn't work with images yet.
https://github.com/budlabs/genmonify/blob/0a83c1805f0639a24d809c1794abe73da14244a2/genmonify#L58

It has to be this:
`$message${__o[img]}${__o[icon]}`

**Comment by budRich** [comment]
thanks, i only tested with icon, will fix and update again.
